from typing import Any, Callable

def bind(target: Window, event: str) -> Callable[[Callable], Callable]: ...

class Document:
    def __getattr__(self, name: str) -> Any: ...
    def __setattr__(self, name: str, value: Any) -> None: ...

document: Document

class Window:
    def __getattr__(self, name: str) -> Any: ...
    def __setattr__(self, name: str, value: Any) -> None: ...
    def requestAnimationFrame(self, callback: Callable[[float], None]) -> None: ...

window: Window
